### ISSUE TITLE
Trouble installing requirements

### ISSUE THREAD

**Issue by Tortillaguy** [yuvraj108c/ComfyUI-Depth-Anything-Tensorrt#3]
After a fresh install of the module from the ComfyUI manager, I followed the instructions and ran `pip install -r requirements.txt`
However, this is the error I received when running pip

```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting cuda-python (from -r requirements.txt (line 1))
  Downloading cuda_python-12.4.0-cp310-cp310-win_amd64.whl.metadata (12 kB)
Collecting tensorrt (from -r requirements.txt (line 2))
  Downloading tensorrt-8.6.1.post1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Adrian\AppData\Local\Temp\pip-install-r7pwndnd\tensorrt_14eb96209b3642c6b050758595e14a19\setup.py", line 103, in <module>
          if disable_internal_pip or nvidia_pip_index_url in parent_command_line() or nvidia_pip_index_url in pip_config_list():
        File "C:\Users\Adrian\AppData\Local\Temp\pip-install-r7pwndnd\tensorrt_14eb96209b3642c6b050758595e14a19\setup.py", line 96, in parent_command_line
          return subprocess.check_output(["ps", "-p", str(pid), "-o", "command", "--no-headers"]).decode()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

This is on Windows 11. Am I missing another dependency?

**Comment by yuvraj108c** [comment]
hi, you need to have cuda/cudnn setup properly on your system. 
Try checking this video: https://www.youtube.com/watch?v=KoCms6vMH6A

**Comment by Tortillaguy** [comment]
Thank you!
